#ifndef GESTURE_DEF_H
#define GESTURE_DEF_H

enum GESTURE_STATE {
	GESTURE_STATE_INVALID = -1,
    GESTURE_STATE_STARTED  = 0,
    GESTURE_STATE_UPDATED  = 1,
    GESTURE_STATE_FINISHED = 2,
    GESTURE_STATE_CANCECLED = 3,
    GESTURE_STATE_MAYBE = 4,
};

enum GESTURE_TYPE {
	GESTURE_TYPE_UNKNOWN = -1,
	GESTURE_TYPE_SCRATCH = 0,
	GESTURE_TYPE_3FLICK = 1,
	GESTURE_TYPE_MULTILONGPRESS = 2,

    GESTURE_TYPE_TAP = 3,
    GESTURE_TYPE_DRAG = 4,
    GESTURE_TYPE_FLICK = 5,
    GESTURE_TYPE_PINCH = 6,
    GESTURE_TYPE_DOUBLECLICK = 7,
	GESTURE_TYPE_2FLICK = 8,
    GESTURE_TYPE_2ROTARY = 9,
    GESTURE_TYPE_2DRAG = 10,
    GESTURE_TYPE_LONGPRESS = 11,
    GESTURE_TYPE_2LONGPRESS = 12,
    GESTURE_TYPE_2TAP = 13,

    GESTURE_TYPE_NUM = 14
};

struct GesturePoint {
	int x;
	int y;
};

struct GestureRect {
	int left;
	int top;
	int right;
	int bottom;
};

#endif /* GESTURE_DEF_H */
