/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_cube_OpenGLJniLib.h"
#include "sys/types.h"
#include "stdio.h"
#include "unistd.h"

#include <android/log.h>
#define LOGJNI(...) __android_log_print(ANDROID_LOG_DEBUG, "Cube", __VA_ARGS__)

#include "Director.h"
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    getFPS
 * Signature: ()F
 */
jfloat Java_com_example_cube_OpenGLJniLib_getFPS
(JNIEnv *env, jclass cls)
{
    LOGJNI("getFPS");
    return Director::instance()->getFps();
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    addTexture
 * Signature: (II)V
 */
void Java_com_example_cube_OpenGLJniLib_addTexture
(JNIEnv *env, jclass cls, jint id, jint txtid, jint w, jint h)
{
    LOGJNI("addTexture id:%d txt:%d w:%d h:%d", id, txtid, w, h);
    Director::instance()->addTexture(id, txtid, w, h);
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    addTextureData
 * Signature: (ILjava/nio/ByteBuffer;II)V
 */
void Java_com_example_cube_OpenGLJniLib_addTextureData
(JNIEnv *env, jclass cls, jint id, jobject obj, jint w, jint h)
{
    return;
    // LOGJNI("addTextureData 000");
    // void* buff = env->GetDirectBufferAddress(obj);    
    // jlong buffsize = env->GetDirectBufferCapacity(obj);
    // LOGJNI("addTextureData :%p %d", buff, buffsize);

    // if (buff == NULL) {
    //     char* data = new char[w*h*4];
    //     for (int i = 0; i < w*h*4; i=i+4) {
    //         data[i] = 0x8f;
    //         data[i+1] = 0;
    //         data[i+2] = 0;
    //         data[i+3] = 0x8f;
    //     }
    //     buff = (void*)data;
    //     LOGJNI("addTextureData badcase!!!");
    // }
    // LOGJNI("addTextureData id:%d buff:%p w:%d h:%d", id, buff, w, h);
    // Director::instance()->addTexture(id, buff, w, h);
}

void Java_com_example_cube_OpenGLJniLib_addTextureByArray
(JNIEnv *env, jclass cls, jint id, jbyteArray data, jint size, jint w, jint h)
{
    jbyte *bytes = env->GetByteArrayElements(data, 0);
    int chars_len = env->GetArrayLength(data);
    char *chars = new char[chars_len + 1];
    memcpy(chars, bytes, chars_len);
    chars[chars_len] = 0;
    env->ReleaseByteArrayElements(data, bytes, 0);

    LOGJNI("addTextureData id:%d buff:%p w:%d h:%d", id, chars, w, h);
    Director::instance()->addTexture(id, (void*)chars, w, h);
    delete [] chars;
    chars = NULL; 
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    addTexture
 * Signature: (II)V
 */
void Java_com_example_cube_OpenGLJniLib_setPlaneTexture
(JNIEnv *env, jclass cls, jint id, jint txtid)
{
    LOGJNI("setPlaneTexture plane:%d txt:%d", id, txtid);
    Director::instance()->setPlaneTexture(id, txtid);
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    rotateCube
 * Signature: (FF)V
 */
void Java_com_example_cube_OpenGLJniLib_rotateCube
(JNIEnv *env, jclass cls, jfloat degrees, jfloat ms)
{
    LOGJNI("rotateCube degrees:%.2f time:%.1f", degrees, ms);
    Director::instance()->rotateCube(degrees, ms);
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    setMode
 * Signature: (I)V
 */
void Java_com_example_cube_OpenGLJniLib_setMode
(JNIEnv *env, jclass cls, jint mode)
{
    LOGJNI("setMode mode:%d", mode);
    Director::instance()->setMode(mode);
}
  
/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    setLayout
 * Signature: (I)V
 */
void Java_com_example_cube_OpenGLJniLib_setLayout
(JNIEnv *env, jclass cls, jint layout)
{
    LOGJNI("setLayout layout:%d", layout);
    Director::instance()->setLayout(layout);
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    initWindow
 * Signature: (II)V
 */
void Java_com_example_cube_OpenGLJniLib_initWindow
(JNIEnv *env, jclass cls, jint w, jint h)
{
    LOGJNI("init");
    setuid(0);
    Director::instance()->init();
    LOGJNI("setWindowSize %d %d", w, h);
    Director::instance()->setWindowSize(w, h);
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    injectTouch
 * Signature: (IFF)V
 */
void Java_com_example_cube_OpenGLJniLib_injectTouch
  (JNIEnv *env, jclass cls, jint action, jfloat x, jfloat y)
{
    LOGJNI("injectTouch %d %.1f %.1f", action, x, y);

    TouchEvent event;
    event.action = action;
    event.x = x;
    event.y = y;
    Director::instance()->injectTouch(event);
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    loopOnce
 * Signature: ()V
 */
void Java_com_example_cube_OpenGLJniLib_loopOnce
  (JNIEnv *env, jclass cls)
{
    // LOGJNI("loop");
    Director::instance()->loop();
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    pause
 * Signature: ()V
 */
void Java_com_example_cube_OpenGLJniLib_pause
  (JNIEnv *env, jclass cls)
{
    LOGJNI("pause");
    // Director::instance()->pause();
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    resume
 * Signature: ()V
 */
void Java_com_example_cube_OpenGLJniLib_resume
  (JNIEnv *env, jclass cls)
{
    LOGJNI("resume");
    // Director::instance()->resume();
}

/*
 * Class:     com_example_cube_OpenGLJniLib
 * Method:    deinit
 * Signature: ()V
 */
void Java_com_example_cube_OpenGLJniLib_deinit
  (JNIEnv *env, jclass cls)
{
    LOGJNI("deinit");
    // Director::instance()->deinit();
}
#ifdef __cplusplus
}
#endif
